name: Performance Tests (JMeter & Gatling)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run JMeter tests
        run: mvn verify -Pjmeter

      - name: Run Gatling tests
        run: mvn gatling:test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: performance-reports
          path: |
            target/jmeter/results/
            target/gatling/
